name: Build and Deploy Presentation

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render presentation
        run: quarto render index.Qmd

      - name: Stage deployment
        run: |
          mkdir -p _deploy
          cp index.html custom.scss styles.css _deploy/
          cp -r index_files/ img/ _deploy/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _deploy
          # destination_dir: en
          keep_files: true
